version: '3.9'

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        VITE_BASE_URL: http://server:3000
    environment:
      - VITE_BASE_URL=http://server:3000
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped
